"""Generate shared browser/server parity data for the Lichess phase divider.

Run from backend/ with the virtualenv active:

    python scripts/gen_game_phase_parity_fixture.py

The fixture is consumed by backend/test_game_phase_parity.py and
src/utils/gamePhase.parity.test.ts. Expected line divisions are derived with an
inline walk rather than app.game_phase.divide(), so assembly and scan-order
regressions are detectable.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

import chess

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.game_phase import backrank_sparse, majors_and_minors, mixedness  # noqa: E402
from app.opening_boundary import OPENING_BOUNDARY_MAX_PROBE_PLY  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = REPO_ROOT / "src" / "utils" / "__fixtures__" / "gamePhaseParity.json"

START = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
MM10 = "1qrbk1r1/8/8/8/8/8/8/R1BQKBNR w - - 0 1"
MM11 = "1qrbk1r1/8/8/8/8/8/8/RNBQKBNR w - - 0 1"
BACKRANK = "rnbqkbnr/pppppppp/8/8/8/RNB2BNR/PPPPPPPP/3QK3 w - - 0 1"
BLACK_BACKRANK = "3qk3/pppppppp/rnb2bnr/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1"
MIX_HI = "rnbqkbnr/2pppp2/2PPPP2/2pppp2/2PPPP2/2pppp2/8/RNBQKBNR w - - 0 1"
MIX_LO = "rnbqkbnr/8/2pppp2/2PPPP2/2pppp2/2PPPP2/8/RNBQKBNR w - - 0 1"
MIX_EXACT = "1n1r1bnr/1ppkpp2/7p/pq1p3R/1P2NPP1/4P1P1/P1PPQ3/R1BK1B2 b - - 3 17"
MM7 = "1qr1k1r1/8/8/8/8/8/8/1QR1K1RN w - - 0 1"
MM6 = "1qr1k1r1/8/8/8/8/8/8/1QR1K1R1 w - - 0 1"

DEVELOPMENT_LINE = [
    "Nf3",
    "Nf6",
    "g3",
    "g6",
    "Bg2",
    "Bg7",
    "d3",
    "d6",
    "Nbd2",
    "Nbd7",
    "b3",
    "b6",
    "Bb2",
    "Bb7",
    "e3",
    "e6",
    "Qe2",
    "Qe7",
]
KNIGHT_SHUFFLE_CYCLE = ["Nf3", "Nf6", "Ng1", "Ng8"]


def fens_after(sans: list[str]) -> list[str]:
    board = chess.Board()
    fens: list[str] = []
    for san in sans:
        board.push_san(san)
        fens.append(board.fen())
    return fens


def is_middlegame(board: chess.Board) -> bool:
    return (
        majors_and_minors(board) <= 10
        or backrank_sparse(board)
        or mixedness(board) > 150
    )


def inline_division(boards: list[chess.Board]) -> tuple[int | None, int | None]:
    middle = next(
        (index for index, board in enumerate(boards) if is_middlegame(board)),
        None,
    )
    end = None
    if middle is not None:
        end = next(
            (
                index
                for index, board in enumerate(boards)
                if majors_and_minors(board) <= 6
            ),
            None,
        )
    if middle is not None and end is not None and not middle < end:
        middle = None
    return middle, end


def build_line(name: str, sans: list[str], raw_fens: list[str] | None = None) -> dict:
    fens = raw_fens if raw_fens is not None else fens_after(sans)
    boards = [chess.Board(), *(chess.Board(fen) for fen in fens)]
    middle, end = inline_division(boards)
    capped_middle, _ = inline_division(boards[: OPENING_BOUNDARY_MAX_PROBE_PLY + 1])
    return {
        "name": name,
        "sans": sans,
        "fens": fens,
        "middle": middle,
        "end": end,
        "opening_ply_count": capped_middle,
    }


def position_record(fen: str) -> dict:
    board = chess.Board(fen)
    major_minor_count = majors_and_minors(board)
    sparse = backrank_sparse(board)
    mix = mixedness(board)
    return {
        "fen": fen,
        "majors_and_minors": major_minor_count,
        "backrank_sparse": sparse,
        "mixedness": mix,
        "is_middlegame": major_minor_count <= 10 or sparse or mix > 150,
    }


def main() -> None:
    shuffle_under_cap = KNIGHT_SHUFFLE_CYCLE * 10
    crossing_past_cap = KNIGHT_SHUFFLE_CYCLE * 20 + DEVELOPMENT_LINE
    crossing_at_cap = [START] * (OPENING_BOUNDARY_MAX_PROBE_PLY - 1) + [BACKRANK]
    crossing_one_past_cap = [START] * OPENING_BOUNDARY_MAX_PROBE_PLY + [BACKRANK]
    lines = [
        build_line("crosses-midgame", DEVELOPMENT_LINE),
        build_line("crossing-on-final-ply", DEVELOPMENT_LINE[:17]),
        build_line("one-ply-before-crossing", DEVELOPMENT_LINE[:16]),
        build_line("end-collapse", [], [MM6]),
        build_line("end-threshold-seven", [], [MM7, MM6]),
        build_line("no-crossing-under-cap", shuffle_under_cap),
        build_line("crossing-at-cap", [], crossing_at_cap),
        build_line("crossing-one-ply-past-cap", [], crossing_one_past_cap),
        build_line("crossing-past-cap", crossing_past_cap),
        build_line("empty-line", []),
    ]
    payload = {
        "_comment": (
            "GENERATED by backend/scripts/gen_game_phase_parity_fixture.py; "
            "do not hand-edit. Shared ground truth pinning app.game_phase to "
            "src/utils/gamePhase.ts."
        ),
        "max_probe_ply": OPENING_BOUNDARY_MAX_PROBE_PLY,
        "positions": [
            position_record(fen)
            for fen in [
                START,
                MM10,
                MM11,
                BACKRANK,
                BLACK_BACKRANK,
                MIX_HI,
                MIX_LO,
                MIX_EXACT,
                MM7,
                MM6,
            ]
        ],
        "lines": lines,
    }
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(payload, indent=2) + "\n")
    print(
        f"wrote {OUT_PATH} ({len(payload['positions'])} positions, {len(lines)} lines)"
    )


if __name__ == "__main__":
    main()
